config:
  app_config:
    name: "Urban Land Cover Change: Uteh/Iwogban and Environs, Benin City (2016–2025)"
    description: ""

  dynamic_world_classes:
    0: "water"
    1: "trees"
    2: "grass"
    3: "flooded vegetation"
    4: "crops"
    5: "shrub and scrub"
    6: "built area"
    7: "bare ground"
    8: "snow and ice"

  dataset:
    raw_dataset: 
      aoi_geojson: "${repo_root:}/data/raw/custom_aoi_geojson/custom_aoi.geojson"
      aoi_lulc: "${repo_root:}/data/raw/custom_aoi_LULC"
      base_data: "${repo_root:}/data/raw/nigeria_wards_data/grid3_nga_boundary_vaccwards.shp"

    processed_dataset:
      aoi_shapefile: "${repo_root:}/data/processed/custom_aoi_shapefile/area_of_interest.shp"


