config:
  app_config:
    name: "Urban Land Cover Change: Uteh/Iwogban and Environs, Benin City (2016–2025)"
    description: ""

  dynamic_world:
    classes:
      0:
        name: "water"
        colour: "#419BDF"
      1:
        name: "trees"
        colour: "#397D49"
      2:
        name: "grass"
        colour: "#88B053"
      3:
        name: "flooded vegetation"
        colour: "#7A87C6"
      4:
        name: "crops"
        colour: "#E49635"
      5:
        name: "shrub and scrub"
        colour: "#DFC35A"
      6:
        name: "built area"
        colour: "#C4281B"
      7:
        name: "bare ground"
        colour: "#A59B8F"
      8:
        name: "snow and ice"
        colour: "#B39FE1"

  dataset:
    raw_dataset: 
      aoi_geojson: "${repo_root:}/data/raw/custom_aoi_geojson/custom_aoi.geojson"
      aoi_lulc: "${repo_root:}/data/raw/custom_aoi_LULC"
      base_data: "${repo_root:}/data/raw/nigeria_wards_data/grid3_nga_boundary_vaccwards.shp"

    processed_dataset:
      aoi_shapefile: "${repo_root:}/data/processed/custom_aoi_shapefile/area_of_interest.shp"

